name: Nightly Build Release

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1/6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Trigger all platform builds
  build-linux:
    uses: ./.github/workflows/linux.yml
    
  build-mac:
    uses: ./.github/workflows/mac.yml
    
  build-windows:
    uses: ./.github/workflows/windows.yml
    
  #build-android:
  #  uses: ./.github/workflows/android.yml

  # Create release with all artifacts
  create-release:
    needs: [build-linux, build-mac, build-windows] #, build-android]
    runs-on: ubuntu-latest
    timeout-minutes: 720  # 12 hours
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: List everything in the repository
        run: |
          echo "Repository contents:"
          ls -R
      
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: firefox-linux.tar.xz
          path: ./artifacts/
      
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: firefox-macos.dmg
          path: ./artifacts/
      
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: firefox-windows.zip
          path: ./artifacts/
      
      #- name: Download Android artifacts
        #uses: actions/download-artifact@v4
        #with:
          #name: firefox-android
          #path: ./artifacts/android/
      
      - name: Create nightly release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: "Nightly Build"
          body: |
            ## Firefox Custom Build - Nightly Release
            
            Automated nightly build created on ${{ github.event.head_commit.timestamp }}
            
            **Platforms included:**
            - 🐧 Linux (tar.xz)
            - 🍎 macOS (dmg)  
            - 🪟 Windows (zip/exe)
            - 🤖 Android (apk)
            
            **Build Information:**
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
          artifacts: |
            ./artifacts/*.tar.xz
            ./artifacts/*.dmg
            ./artifacts/*.zip
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
